import type { ModelProfile } from "@/src/shared/validation/model-profile.schema";

/**
 * 모델 카탈로그 시드 데이터
 *
 * 마지막 검증일 기준으로 작성. 실제 가격/컨텍스트 수치는 공식 문서 기준.
 * 변동 가능한 값(무료 한도 등)은 lastVerifiedAt으로 구분.
 * 확인되지 않은 값은 보수적으로 undefined 처리.
 */
export const MODEL_CATALOG_SEED: ModelProfile[] = [
  // ── OpenAI 계열 ──────────────────────────────────────────────
  {
    id: "openai/gpt-4o",
    provider: "OpenAI",
    displayName: "GPT-4o",
    family: "GPT-4",
    accessType: ["web", "api"],
    isOpenWeight: false,
    isFreeExecutable: true,
    freeExecutionProvider: "ChatGPT 무료 플랜 (제한적)",
    inputModalities: ["text", "image", "file"],
    outputModalities: ["text"],
    contextWindow: 128000,
    maxOutputTokens: 16384,
    supportsReasoning: false,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    supportsWebSearch: true,
    taskScores: {
      general: 90,
      coding: 88,
      reasoning: 85,
      writing: 90,
      translation: 88,
      summarization: 90,
      longContext: 82,
    },
    qualityTier: 5,
    speedTier: 4,
    costTier: 4,
    stabilityTier: 5,
    strengths: [
      "멀티모달 입력 지원 (텍스트, 이미지, 파일)",
      "도구 호출 및 구조화 출력 지원",
      "웹 검색 통합 가능",
      "광범위한 작업에서 높은 품질",
    ],
    limitations: [
      "API 사용 시 유료",
      "무료 플랜은 사용량 제한 있음",
      "최신 정보 학습 한계",
    ],
    status: "active",
    lastVerifiedAt: "2025-07-01T00:00:00Z",
  },
  {
    id: "openai/gpt-4o-mini",
    provider: "OpenAI",
    displayName: "GPT-4o mini",
    family: "GPT-4",
    accessType: ["web", "api"],
    isOpenWeight: false,
    isFreeExecutable: false,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    contextWindow: 128000,
    maxOutputTokens: 16384,
    supportsReasoning: false,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    supportsWebSearch: false,
    taskScores: {
      general: 78,
      coding: 76,
      reasoning: 72,
      writing: 78,
      translation: 80,
      summarization: 80,
      longContext: 75,
    },
    qualityTier: 3,
    speedTier: 5,
    costTier: 1,
    stabilityTier: 5,
    strengths: [
      "빠른 응답 속도",
      "낮은 API 비용",
      "구조화 출력 지원",
      "긴 컨텍스트 처리",
    ],
    limitations: [
      "복잡한 추론은 상위 모델보다 낮은 정확도",
      "이미지 이해 능력이 GPT-4o보다 제한적",
    ],
    status: "active",
    lastVerifiedAt: "2025-07-01T00:00:00Z",
  },
  {
    id: "openai/o4-mini",
    provider: "OpenAI",
    displayName: "o4-mini",
    family: "OpenAI o-series",
    accessType: ["web", "api"],
    isOpenWeight: false,
    isFreeExecutable: true,
    freeExecutionProvider: "ChatGPT 무료 플랜 (제한적)",
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    contextWindow: 200000,
    maxOutputTokens: 100000,
    supportsReasoning: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    supportsWebSearch: false,
    taskScores: {
      general: 82,
      coding: 92,
      reasoning: 95,
      writing: 75,
      translation: 72,
      summarization: 78,
      longContext: 88,
    },
    qualityTier: 5,
    speedTier: 3,
    costTier: 2,
    stabilityTier: 4,
    strengths: [
      "수학·코딩·과학 추론에서 최상위 성능",
      "200K 대용량 컨텍스트",
      "체인-오브-쏫 내부 추론",
    ],
    limitations: [
      "일반 대화·창작은 비추론 모델보다 느림",
      "응답 지연 있음 (추론 시간)",
    ],
    status: "active",
    lastVerifiedAt: "2025-07-01T00:00:00Z",
  },

  // ── Google Gemini 계열 ────────────────────────────────────────
  {
    id: "google/gemini-2.5-pro",
    provider: "Google",
    displayName: "Gemini 2.5 Pro",
    family: "Gemini 2.5",
    accessType: ["web", "api"],
    isOpenWeight: false,
    isFreeExecutable: true,
    freeExecutionProvider: "Google AI Studio 무료 티어",
    inputModalities: ["text", "image", "audio", "video", "file"],
    outputModalities: ["text"],
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    supportsReasoning: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    supportsWebSearch: true,
    taskScores: {
      general: 92,
      coding: 90,
      reasoning: 95,
      writing: 88,
      translation: 88,
      summarization: 90,
      longContext: 98,
    },
    qualityTier: 5,
    speedTier: 3,
    costTier: 3,
    stabilityTier: 4,
    strengths: [
      "100만 토큰 컨텍스트 윈도우",
      "멀티모달 입력 (텍스트, 이미지, 오디오, 영상, 파일)",
      "복잡한 추론에서 최상위 성능",
      "Google AI Studio에서 무료 사용 가능",
    ],
    limitations: [
      "응답 속도가 빠른 모델보다 느림",
      "무료 API 호출 한도가 있음",
      "preview 기능은 안정성 변동 가능",
    ],
    status: "active",
    lastVerifiedAt: "2025-07-01T00:00:00Z",
  },
  {
    id: "google/gemini-2.5-flash",
    provider: "Google",
    displayName: "Gemini 2.5 Flash",
    family: "Gemini 2.5",
    accessType: ["web", "api"],
    isOpenWeight: false,
    isFreeExecutable: true,
    freeExecutionProvider: "Google AI Studio 무료 티어",
    inputModalities: ["text", "image", "audio", "video", "file"],
    outputModalities: ["text"],
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    supportsReasoning: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    supportsWebSearch: true,
    taskScores: {
      general: 85,
      coding: 84,
      reasoning: 88,
      writing: 82,
      translation: 84,
      summarization: 86,
      longContext: 92,
    },
    qualityTier: 4,
    speedTier: 5,
    costTier: 1,
    stabilityTier: 4,
    strengths: [
      "빠른 속도와 낮은 비용",
      "100만 토큰 컨텍스트",
      "멀티모달 지원",
      "무료 API 사용 가능",
    ],
    limitations: [
      "Gemini 2.5 Pro 대비 복잡한 추론 성능 다소 낮음",
      "무료 티어 사용량 제한",
    ],
    status: "active",
    lastVerifiedAt: "2025-07-01T00:00:00Z",
  },

  // ── Anthropic Claude 계열 ─────────────────────────────────────
  {
    id: "anthropic/claude-sonnet-4-5",
    provider: "Anthropic",
    displayName: "Claude Sonnet 4.5",
    family: "Claude 4",
    accessType: ["web", "api"],
    isOpenWeight: false,
    isFreeExecutable: true,
    freeExecutionProvider: "Claude.ai 무료 플랜 (제한적)",
    inputModalities: ["text", "image", "file"],
    outputModalities: ["text"],
    contextWindow: 200000,
    maxOutputTokens: 64000,
    supportsReasoning: false,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    supportsWebSearch: false,
    taskScores: {
      general: 88,
      coding: 87,
      reasoning: 83,
      writing: 92,
      translation: 85,
      summarization: 90,
      longContext: 88,
    },
    qualityTier: 4,
    speedTier: 4,
    costTier: 3,
    stabilityTier: 5,
    strengths: [
      "글쓰기·편집·요약에서 우수한 품질",
      "200K 긴 컨텍스트",
      "안전하고 일관된 출력",
      "코딩 보조에 강점",
    ],
    limitations: [
      "API 사용 시 유료",
      "웹 검색 기본 미지원",
      "이미지 생성 불가",
    ],
    status: "active",
    lastVerifiedAt: "2025-07-01T00:00:00Z",
  },
  {
    id: "anthropic/claude-haiku-4-5",
    provider: "Anthropic",
    displayName: "Claude Haiku 4.5",
    family: "Claude 4",
    accessType: ["api"],
    isOpenWeight: false,
    isFreeExecutable: false,
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    contextWindow: 200000,
    maxOutputTokens: 64000,
    supportsReasoning: false,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    supportsWebSearch: false,
    taskScores: {
      general: 76,
      coding: 74,
      reasoning: 70,
      writing: 78,
      translation: 76,
      summarization: 78,
      longContext: 75,
    },
    qualityTier: 3,
    speedTier: 5,
    costTier: 1,
    stabilityTier: 5,
    strengths: [
      "Claude 라인에서 가장 빠르고 저렴",
      "단순~중간 수준 작업에 효율적",
      "구조화 출력 및 도구 호출 지원",
    ],
    limitations: [
      "복잡한 추론 작업에서 성능 제한",
      "무료 실행 경로 없음",
    ],
    status: "active",
    lastVerifiedAt: "2025-07-01T00:00:00Z",
  },

  // ── Google Gemma (오픈 웨이트) ────────────────────────────────
  {
    id: "google/gemma-3-27b",
    provider: "Google",
    displayName: "Gemma 3 27B",
    family: "Gemma 3",
    accessType: ["api", "open-weight", "local"],
    isOpenWeight: true,
    isFreeExecutable: true,
    freeExecutionProvider: "Hugging Face / Ollama / OpenRouter 무료 티어",
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    contextWindow: 128000,
    maxOutputTokens: undefined,
    supportsReasoning: false,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    supportsWebSearch: false,
    taskScores: {
      general: 75,
      coding: 72,
      reasoning: 74,
      writing: 73,
      translation: 70,
      summarization: 74,
      longContext: 72,
    },
    qualityTier: 3,
    speedTier: 3,
    costTier: 0,
    stabilityTier: 3,
    strengths: [
      "완전 오픈 가중치 (상업 이용 가능)",
      "로컬 실행 가능",
      "다국어 및 이미지 입력 지원",
      "무료 실행 경로 다양",
    ],
    limitations: [
      "동급 유료 모델 대비 성능 낮음",
      "로컬 실행 시 고사양 GPU 필요 (27B)",
    ],
    status: "active",
    lastVerifiedAt: "2025-07-01T00:00:00Z",
  },

  // ── Meta Llama 계열 ──────────────────────────────────────────
  {
    id: "meta/llama-3.3-70b",
    provider: "Meta",
    displayName: "Llama 3.3 70B Instruct",
    family: "Llama 3",
    accessType: ["api", "open-weight", "local"],
    isOpenWeight: true,
    isFreeExecutable: true,
    freeExecutionProvider: "Groq 무료 티어 / OpenRouter 무료 티어",
    inputModalities: ["text"],
    outputModalities: ["text"],
    contextWindow: 128000,
    maxOutputTokens: undefined,
    supportsReasoning: false,
    supportsToolCalling: true,
    supportsStructuredOutput: false,
    supportsWebSearch: false,
    taskScores: {
      general: 80,
      coding: 78,
      reasoning: 79,
      writing: 78,
      translation: 74,
      summarization: 80,
      longContext: 76,
    },
    qualityTier: 4,
    speedTier: 4,
    costTier: 0,
    stabilityTier: 4,
    strengths: [
      "오픈 가중치로 자유로운 활용",
      "Groq에서 무료 고속 추론 가능",
      "범용 성능 우수",
    ],
    limitations: [
      "구조화 출력 공식 미지원",
      "번역 성능이 다국어 전용 모델보다 낮음",
    ],
    status: "active",
    lastVerifiedAt: "2025-07-01T00:00:00Z",
  },
  {
    id: "meta/llama-3.1-8b",
    provider: "Meta",
    displayName: "Llama 3.1 8B Instruct",
    family: "Llama 3",
    accessType: ["api", "open-weight", "local"],
    isOpenWeight: true,
    isFreeExecutable: true,
    freeExecutionProvider: "Groq 무료 티어 / Ollama 로컬",
    inputModalities: ["text"],
    outputModalities: ["text"],
    contextWindow: 128000,
    maxOutputTokens: undefined,
    supportsReasoning: false,
    supportsToolCalling: false,
    supportsStructuredOutput: false,
    supportsWebSearch: false,
    taskScores: {
      general: 68,
      coding: 65,
      reasoning: 62,
      writing: 66,
      translation: 60,
      summarization: 68,
      longContext: 65,
    },
    qualityTier: 2,
    speedTier: 5,
    costTier: 0,
    stabilityTier: 4,
    strengths: [
      "매우 빠른 추론 속도",
      "로컬 실행이 가능한 소형 모델",
      "무료로 사용 가능",
    ],
    limitations: [
      "복잡한 작업에서 성능 제한",
      "도구 호출 미지원",
    ],
    status: "active",
    lastVerifiedAt: "2025-07-01T00:00:00Z",
  },

  // ── Mistral 계열 ─────────────────────────────────────────────
  {
    id: "mistral/mistral-small-3.1",
    provider: "Mistral",
    displayName: "Mistral Small 3.1",
    family: "Mistral Small",
    accessType: ["api", "open-weight", "local"],
    isOpenWeight: true,
    isFreeExecutable: true,
    freeExecutionProvider: "Mistral API 무료 티어 / Ollama 로컬",
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    contextWindow: 128000,
    maxOutputTokens: undefined,
    supportsReasoning: false,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    supportsWebSearch: false,
    taskScores: {
      general: 76,
      coding: 74,
      reasoning: 72,
      writing: 74,
      translation: 78,
      summarization: 76,
      longContext: 72,
    },
    qualityTier: 3,
    speedTier: 5,
    costTier: 0,
    stabilityTier: 4,
    strengths: [
      "오픈 가중치 + 이미지 입력 지원",
      "빠르고 효율적",
      "유럽 법규 준수에 유리 (EU 기업)",
      "다국어 성능 우수",
    ],
    limitations: [
      "복잡한 추론 작업에서 대형 모델 대비 낮은 성능",
    ],
    status: "active",
    lastVerifiedAt: "2025-07-01T00:00:00Z",
  },

  // ── 코딩/추론 특화 오픈 모델 ─────────────────────────────────
  {
    id: "deepseek/deepseek-r1",
    provider: "DeepSeek",
    displayName: "DeepSeek R1",
    family: "DeepSeek R-series",
    accessType: ["api", "open-weight", "local"],
    isOpenWeight: true,
    isFreeExecutable: true,
    freeExecutionProvider: "DeepSeek API 무료 티어 / OpenRouter 무료 티어",
    inputModalities: ["text"],
    outputModalities: ["text"],
    contextWindow: 128000,
    maxOutputTokens: undefined,
    supportsReasoning: true,
    supportsToolCalling: false,
    supportsStructuredOutput: false,
    supportsWebSearch: false,
    taskScores: {
      general: 82,
      coding: 92,
      reasoning: 95,
      writing: 70,
      translation: 68,
      summarization: 75,
      longContext: 80,
    },
    qualityTier: 5,
    speedTier: 2,
    costTier: 0,
    stabilityTier: 3,
    strengths: [
      "수학·코딩·과학 추론에서 최상위 오픈 모델",
      "체인-오브-쏫 내부 추론 공개",
      "오픈 가중치로 자유로운 활용",
      "무료 실행 가능",
    ],
    limitations: [
      "응답 속도가 느림 (추론 시간)",
      "일반 대화·창작에서 성능 상대적으로 낮음",
      "도구 호출 및 구조화 출력 미지원",
      "안정성이 상용 모델보다 낮을 수 있음",
    ],
    status: "active",
    lastVerifiedAt: "2025-07-01T00:00:00Z",
  },
  {
    id: "qwen/qwen2.5-coder-32b",
    provider: "Alibaba",
    displayName: "Qwen2.5-Coder-32B",
    family: "Qwen2.5-Coder",
    accessType: ["api", "open-weight", "local"],
    isOpenWeight: true,
    isFreeExecutable: true,
    freeExecutionProvider: "OpenRouter 무료 티어 / Ollama 로컬",
    inputModalities: ["text"],
    outputModalities: ["text"],
    contextWindow: 131072,
    maxOutputTokens: undefined,
    supportsReasoning: false,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    supportsWebSearch: false,
    taskScores: {
      general: 72,
      coding: 90,
      reasoning: 78,
      writing: 65,
      translation: 70,
      summarization: 68,
      longContext: 76,
    },
    qualityTier: 4,
    speedTier: 3,
    costTier: 0,
    stabilityTier: 3,
    strengths: [
      "코딩 특화 오픈 모델에서 최상위 성능",
      "오픈 가중치 및 로컬 실행 가능",
      "131K 컨텍스트",
      "다국어 코딩 지원",
    ],
    limitations: [
      "코딩 외 일반 작업에서 성능 제한",
      "로컬 실행에 고사양 GPU 필요 (32B)",
    ],
    status: "active",
    lastVerifiedAt: "2025-07-01T00:00:00Z",
  },
];
