import type { ModelProfile } from "@/src/shared/validation/model-profile.schema";

/**
 * ModelFit 추천용 카탈로그.
 *
 * - lastVerifiedAt: 제조사 공식 문서/공식 모델 페이지 확인일
 * - taskScores: 서로 다른 공급자의 모델을 추천하기 위한 상대적 휴리스틱 점수
 *   (공식 벤치마크 점수를 그대로 옮긴 값이 아님)
 * - 변동이 빠른 무료 한도/가격 숫자는 추천 로직에 직접 하드코딩하지 않는다.
 */
export const MODEL_CATALOG_SEED: ModelProfile[] = [
  // ── OpenAI ───────────────────────────────────────────────────
  {
    id: "openai/gpt-6-astra",
    provider: "OpenAI",
    displayName: "GPT-6 Astra",
    family: "GPT-6",
    accessType: ["web", "api"],
    isOpenWeight: false,
    isFreeExecutable: false,
    inputModalities: ["text", "image", "file"],
    outputModalities: ["text"],
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    supportsReasoning: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    supportsWebSearch: true,
    taskScores: {
      general: 98,
      coding: 99,
      reasoning: 99,
      writing: 96,
      translation: 94,
      summarization: 96,
      longContext: 99,
    },
    qualityTier: 5,
    speedTier: 3,
    costTier: 5,
    stabilityTier: 4,
    strengths: [
      "복잡한 추론·코딩·리서치·컴퓨터 사용에 적합",
      "100만 토큰 이상 컨텍스트와 128K 출력 지원",
      "웹 검색·파일 검색·컴퓨터 사용 등 도구 지원",
    ],
    limitations: [
      "고성능 모델이라 비용이 높은 편",
      "단순 반복 작업에는 더 가벼운 모델이 효율적일 수 있음",
    ],
    status: "active",
    sourceUpdatedAt: "2026-09-03T00:00:00Z",
    lastVerifiedAt: "2026-09-20T00:00:00Z",
  },
  {
    id: "openai/gpt-5.6-terra",
    provider: "OpenAI",
    displayName: "GPT-5.6 Terra",
    family: "GPT-5.6",
    accessType: ["api"],
    isOpenWeight: false,
    isFreeExecutable: false,
    inputModalities: ["text", "image", "file"],
    outputModalities: ["text"],
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    supportsReasoning: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    supportsWebSearch: true,
    taskScores: {
      general: 92,
      coding: 93,
      reasoning: 93,
      writing: 91,
      translation: 90,
      summarization: 92,
      longContext: 98,
    },
    qualityTier: 4,
    speedTier: 4,
    costTier: 3,
    stabilityTier: 5,
    strengths: [
      "지능과 비용의 균형을 목표로 한 범용 모델",
      "긴 컨텍스트와 도구 호출을 함께 활용하는 업무에 적합",
    ],
    limitations: [
      "최고 난도 작업에서는 GPT-6 Astra보다 보수적인 선택",
      "API 사용은 유료",
    ],
    status: "active",
    sourceUpdatedAt: "2026-02-16T00:00:00Z",
    lastVerifiedAt: "2026-09-20T00:00:00Z",
  },
  {
    id: "openai/gpt-5.6-luna",
    provider: "OpenAI",
    displayName: "GPT-5.6 Luna",
    family: "GPT-5.6",
    accessType: ["web", "api"],
    isOpenWeight: false,
    isFreeExecutable: true,
    freeExecutionProvider: "ChatGPT Free/Go (사용량 제한 가능)",
    inputModalities: ["text", "image", "file"],
    outputModalities: ["text"],
    contextWindow: 1050000,
    maxOutputTokens: 128000,
    supportsReasoning: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    supportsWebSearch: true,
    taskScores: {
      general: 84,
      coding: 84,
      reasoning: 83,
      writing: 84,
      translation: 85,
      summarization: 86,
      longContext: 96,
    },
    qualityTier: 3,
    speedTier: 5,
    costTier: 1,
    stabilityTier: 5,
    strengths: [
      "비용 민감·대량 요청에 적합",
      "빠른 응답과 긴 컨텍스트의 균형",
      "도구 호출과 구조화 출력 지원",
    ],
    limitations: [
      "복잡한 장기 추론은 상위 모델보다 품질이 낮을 수 있음",
      "무료 웹 사용량은 계정/플랜에 따라 제한될 수 있음",
    ],
    status: "active",
    sourceUpdatedAt: "2026-02-16T00:00:00Z",
    lastVerifiedAt: "2026-09-20T00:00:00Z",
  },

  // ── Google ───────────────────────────────────────────────────
  {
    id: "google/gemini-3.8-flash",
    provider: "Google",
    displayName: "Gemini 3.8 Flash",
    family: "Gemini 3.8",
    accessType: ["web", "api"],
    isOpenWeight: false,
    isFreeExecutable: true,
    freeExecutionProvider: "Google AI Studio / Gemini 웹 (한도는 계정에 따라 다름)",
    inputModalities: ["text", "image", "audio", "video", "file"],
    outputModalities: ["text"],
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    supportsReasoning: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    supportsWebSearch: true,
    taskScores: {
      general: 95,
      coding: 97,
      reasoning: 96,
      writing: 91,
      translation: 92,
      summarization: 94,
      longContext: 99,
    },
    qualityTier: 5,
    speedTier: 5,
    costTier: 2,
    stabilityTier: 5,
    strengths: [
      "장기 소프트웨어 엔지니어링·에이전트 작업에 강점",
      "100만 토큰 컨텍스트와 멀티모달 입력 지원",
      "속도와 비용 효율을 유지하면서 높은 추론 성능",
    ],
    limitations: [
      "복잡한 작업에서는 reasoning level에 따라 지연·토큰 사용량이 증가할 수 있음",
    ],
    status: "active",
    sourceUpdatedAt: "2026-09-02T00:00:00Z",
    lastVerifiedAt: "2026-09-20T00:00:00Z",
  },

  // ── Anthropic ────────────────────────────────────────────────
  {
    id: "anthropic/claude-fable-5-1",
    provider: "Anthropic",
    displayName: "Claude Fable 5.1",
    family: "Claude 5.1",
    accessType: ["web", "api"],
    isOpenWeight: false,
    isFreeExecutable: false,
    inputModalities: ["text", "image", "file"],
    outputModalities: ["text"],
    supportsReasoning: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    supportsWebSearch: true,
    taskScores: {
      general: 97,
      coding: 99,
      reasoning: 98,
      writing: 98,
      translation: 93,
      summarization: 97,
      longContext: 98,
    },
    qualityTier: 5,
    speedTier: 3,
    costTier: 5,
    stabilityTier: 4,
    strengths: [
      "코딩·지식 업무·장시간 에이전트 작업에 특화",
      "코드베이스 전체를 다루는 기능 구현·리뷰에 강점",
      "문서 중심의 복합 전문 업무에 적합",
    ],
    limitations: [
      "고성능 모델이라 비용이 높은 편",
      "사이버보안·생명과학 일부 요청은 안전장치에 따라 제한될 수 있음",
    ],
    status: "active",
    sourceUpdatedAt: "2026-09-01T00:00:00Z",
    lastVerifiedAt: "2026-09-20T00:00:00Z",
  },
  {
    id: "anthropic/claude-sonnet-5",
    provider: "Anthropic",
    displayName: "Claude Sonnet 5",
    family: "Claude 5",
    accessType: ["web", "api"],
    isOpenWeight: false,
    isFreeExecutable: false,
    inputModalities: ["text", "image", "file"],
    outputModalities: ["text"],
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    supportsReasoning: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    supportsWebSearch: true,
    taskScores: {
      general: 95,
      coding: 97,
      reasoning: 96,
      writing: 97,
      translation: 93,
      summarization: 96,
      longContext: 99,
    },
    qualityTier: 5,
    speedTier: 4,
    costTier: 3,
    stabilityTier: 5,
    strengths: [
      "속도와 지능의 균형이 좋은 Claude 범용 모델",
      "코딩·문서 작성·장문 분석에 강점",
      "100만 토큰 컨텍스트와 adaptive thinking 지원",
    ],
    limitations: [
      "단순 대량 처리에서는 더 저렴한 모델이 유리할 수 있음",
    ],
    status: "active",
    sourceUpdatedAt: "2026-06-30T00:00:00Z",
    lastVerifiedAt: "2026-09-20T00:00:00Z",
  },

  // ── Meta open-weight ─────────────────────────────────────────
  {
    id: "meta/llama-4-maverick",
    provider: "Meta",
    displayName: "Llama 4 Maverick",
    family: "Llama 4",
    accessType: ["api", "open-weight", "local"],
    isOpenWeight: true,
    isFreeExecutable: true,
    freeExecutionProvider: "오픈 웨이트 로컬 실행 (컴퓨팅 자원 필요)",
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    supportsReasoning: true,
    supportsToolCalling: true,
    supportsStructuredOutput: false,
    supportsWebSearch: false,
    taskScores: {
      general: 87,
      coding: 86,
      reasoning: 87,
      writing: 84,
      translation: 84,
      summarization: 86,
      longContext: 88,
    },
    qualityTier: 4,
    speedTier: 4,
    costTier: 0,
    stabilityTier: 4,
    strengths: [
      "Meta의 고성능 오픈 웨이트 멀티모달 모델",
      "이미지·텍스트 이해와 빠른 응답에 강점",
      "직접 호스팅해 데이터와 실행 환경을 통제 가능",
    ],
    limitations: [
      "로컬 실행에는 큰 GPU 자원이 필요",
      "호스팅 방식에 따라 실제 속도·비용이 크게 달라짐",
    ],
    status: "active",
    sourceUpdatedAt: "2025-04-05T00:00:00Z",
    lastVerifiedAt: "2026-09-20T00:00:00Z",
  },
  {
    id: "meta/llama-4-scout",
    provider: "Meta",
    displayName: "Llama 4 Scout",
    family: "Llama 4",
    accessType: ["api", "open-weight", "local"],
    isOpenWeight: true,
    isFreeExecutable: true,
    freeExecutionProvider: "오픈 웨이트 로컬 실행 (컴퓨팅 자원 필요)",
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    contextWindow: 10000000,
    supportsReasoning: true,
    supportsToolCalling: true,
    supportsStructuredOutput: false,
    supportsWebSearch: false,
    taskScores: {
      general: 82,
      coding: 82,
      reasoning: 83,
      writing: 80,
      translation: 81,
      summarization: 87,
      longContext: 99,
    },
    qualityTier: 4,
    speedTier: 4,
    costTier: 0,
    stabilityTier: 4,
    strengths: [
      "10M 컨텍스트 윈도우를 지원하는 오픈 웨이트 모델",
      "대량 문서·긴 코드베이스 분석에 유리",
      "멀티모달 입력과 직접 호스팅 지원",
    ],
    limitations: [
      "긴 컨텍스트 최대치를 실제 활용하려면 상당한 추론 자원이 필요",
      "호스팅 환경에 따라 체감 성능 차이가 큼",
    ],
    status: "active",
    sourceUpdatedAt: "2025-04-05T00:00:00Z",
    lastVerifiedAt: "2026-09-20T00:00:00Z",
  },

  // ── DeepSeek ─────────────────────────────────────────────────
  {
    id: "deepseek/deepseek-v4-pro",
    provider: "DeepSeek",
    displayName: "DeepSeek V4 Pro",
    family: "DeepSeek V4",
    accessType: ["web", "api", "open-weight"],
    isOpenWeight: true,
    isFreeExecutable: true,
    freeExecutionProvider: "오픈 웨이트 직접 실행 / DeepSeek 웹 (정책에 따라 제한)",
    inputModalities: ["text"],
    outputModalities: ["text"],
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    supportsReasoning: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    supportsWebSearch: false,
    taskScores: {
      general: 92,
      coding: 97,
      reasoning: 97,
      writing: 85,
      translation: 87,
      summarization: 90,
      longContext: 98,
    },
    qualityTier: 5,
    speedTier: 3,
    costTier: 1,
    stabilityTier: 4,
    strengths: [
      "코딩·추론·에이전트 작업에 강한 오픈 모델",
      "100만 토큰 컨텍스트와 reasoning effort 지원",
      "OpenAI 호환 Responses API 지원",
    ],
    limitations: [
      "비전 입력은 지원하지 않음",
      "웹 서비스와 API의 제공 모델/정책이 달라질 수 있음",
    ],
    status: "active",
    sourceUpdatedAt: "2026-08-13T00:00:00Z",
    lastVerifiedAt: "2026-09-20T00:00:00Z",
  },
  {
    id: "deepseek/deepseek-flash",
    provider: "DeepSeek",
    displayName: "DeepSeek V4.1 Flash",
    family: "DeepSeek V4",
    accessType: ["web", "api", "open-weight"],
    isOpenWeight: true,
    isFreeExecutable: true,
    freeExecutionProvider: "오픈 웨이트 직접 실행 / DeepSeek 웹 (정책에 따라 제한)",
    inputModalities: ["text", "image"],
    outputModalities: ["text"],
    contextWindow: 1000000,
    maxOutputTokens: 384000,
    supportsReasoning: true,
    supportsToolCalling: true,
    supportsStructuredOutput: true,
    supportsWebSearch: false,
    taskScores: {
      general: 88,
      coding: 94,
      reasoning: 93,
      writing: 83,
      translation: 85,
      summarization: 88,
      longContext: 98,
    },
    qualityTier: 4,
    speedTier: 5,
    costTier: 1,
    stabilityTier: 4,
    strengths: [
      "빠르고 경제적인 코딩·에이전트 모델",
      "이미지 입력·도구 호출·JSON 출력 지원",
      "100만 토큰 컨텍스트와 오픈 웨이트 제공",
    ],
    limitations: [
      "최고 난도 추론에서는 Pro급 모델이 더 적합할 수 있음",
    ],
    status: "active",
    sourceUpdatedAt: "2026-09-11T00:00:00Z",
    lastVerifiedAt: "2026-09-20T00:00:00Z",
  },
];
